version: '3.8'

services:
  openai-to-gemini:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      # Map host port 8050 to container port 7860 (for Hugging Face compatibility)
      - "8050:7860"
    volumes:
      - ./credentials:/app/credentials
    environment:
      # Directory where credential files are stored (used by credential manager)
      - CREDENTIALS_DIR=/app/credentials
      # API key for authentication (default: 123456)
      - API_KEY=123456
      # Enable/disable fake streaming (default: false)
      - FAKE_STREAMING=false
      # Interval for fake streaming keep-alive messages (default: 1.0)
      - FAKE_STREAMING_INTERVAL=1.0
    restart: unless-stopped
